---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agent.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  API_KEY: {{ required "config.apiKey is required" .Values.config.apiKey | quote }}
